Default: &defaults
  user: socr
  password: abracadabra
  host: localhost
  port: 5432
  database: socr
  poolsize: 10

Development:
  <<: *defaults

Testing:
  connstr: service=local
  <<: *defaults

Staging:
  connstr: service=local
  poolsize: 100
  <<: *defaults

Production:
  connstr: service=local
  poolsize: 100
  <<: *defaults
